### ISSUE TITLE
custom Ing 定制

### ISSUE THREAD

**Issue by wjz304** [wjz304/Redpill_CustomBuild#1]
{"platform":"DS3622xs+", "version":"7.0.1-42218", "jun":"1", "ext":"r8125"}

**Comment by zhengchao666abc** [comment]
{"platform":"DS918+", "version":"7.1.1-42951", "jun":"1", "ext":"r8125,r8168"}

**Comment by lichangfeng-1** [comment]
{"platform":"DS3622xs+", "version":"7.0.1-42218", "jun":"1", "ext":"ixgbe"}

**Comment by wjz304** [comment]
https://user-images.githubusercontent.com/5615843/187615519-53a6dcf5-a5e2-4731-8889-9eee8955a977.mp4

**Comment by wjz304** [comment]
![20220831154205](https://user-images.githubusercontent.com/5615843/187622659-44df8ac4-0f38-4b7b-9da0-1dd620d96bce.png)

**Comment by wjz304** [comment]
![RTLDCB UK% NS2{6@_ 79WV](https://user-images.githubusercontent.com/5615843/207922990-deeeaae9-d905-44bc-8bc3-f98e94b29355.gif)
