### ISSUE TITLE
Custom Redpill

### ISSUE THREAD

**Issue by wzzgz** [wjz304/Redpill_CustomBuild#10015]
{"platform":"DS918+","version":"7.1.0-42661","maxdisks":"6","maxlanport":"1","internalportcfg":"0xffff","netif_num":"1","vid":"0x0951","pid":"0x1643","diskidxmap":"00","sataportmap":"6","sasidxmap":"0","ext":"r8168","exp":"pocopico","jun":"1","dev":"1"}

**Comment by wzzgz** [comment]
好东西！

**Comment by wjz304** [comment]
> 好东西！

好东西你不点小星星
