### ISSUE TITLE
Custom 测试直接页面提交

### ISSUE THREAD

**Issue by htmambo** [wjz304/Redpill_CustomBuild#103]
{"platform":"DS3615xs","version":"7.1.0-42661","map":"","dtb":"","sn":"","mac":"","usb":"0x0001, 0x46f4","ext":"vmw_pvscsi,ixgbe.vanilla,megaraid_sas,tg3,sky2","exp":"pocopico","jun":"0"}

**Comment by htmambo** [comment]
这个出错是不是因为哪种机型不支持某个Ext造成的？

**Comment by wjz304** [comment]
是的

**Comment by htmambo** [comment]
那后面可能要考虑这种互斥或者某种型号不支持的ext的处理了。我看人脚本 自己在编译的时候好像能检测这种型号支持的驱动来着。
