### ISSUE TITLE
Custom Jepson

### ISSUE THREAD

**Issue by one6ng** [wjz304/Redpill_CustomBuild#1052]
{"platform":"DS3615xs","version":"7.1.1-42951","map":"0,10","sn":"1682LWN087500","mac":"0011329f2268,0011329f2269","usb":"0x0781, 0x5571","ext":"tg3","exp":"pocopico","jun":"1"}

**Comment by wjz304** [comment]
看说明，编不过

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/187480025-330acd4c-8779-4d33-b5e2-6918c71c9c2f.png)
