### ISSUE TITLE
Custom suchas

### ISSUE THREAD

**Issue by suchas2022** [wjz304/Redpill_CustomBuild#106]
{"platform":"DS918+","version":"7.1.0-42661","map":"0,6","dtb":"","sn":"","mac":"","usb":"0x0001, 0x46f4","ext":"rtl8150,r8169,r8168,r8152,r8125,r8101,vmxnet3,e1000,e1000e","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
map 第二个数的位数要是第一个数的2倍，第一个数 是一位，第二个数就要两位

**Comment by suchas2022** [comment]
> map 第二个数的位数要是第一个数的2倍，第一个数 是一位，第二个数就要两位

好的，我再试试，多谢！多谢！
