### ISSUE TITLE
Custom......................3622xs

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#1061]
{
  "platform": "DS3622xs+",
  "version": "7.0.1-42218",
  "map": "1,10",
  "usb": "0x6544, 0x0930",
  "jun": "1",
  "exp": "jumkey",
  "ext": "r8125, e1000, e1000e, vmxnet3, mpt3sas, mptsas, mpt2sas*, megaraid_sas, ixgbe, ixgbevf"
}

**Comment by wjz304** [comment]
带*号 是有bug，编不过，我才加了*号 不让你们选

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/187480218-f56884f1-9142-4a97-a13b-ace990c81d5f.png)

**Comment by wjz304** [comment]
> 有点具体了。我才查到这个LSI2308就是唯独带*的、好尴尬

没办法啦，[pocopico](https://github.com/pocopico) 大的库里实际就是没有 DS3622xs+ 的 mpt2sas，
![image](https://user-images.githubusercontent.com/5615843/187480549-8266cf10-2293-414e-9bba-da94ae716af7.png)

**Comment by wjz304** [comment]
不过 好像3622 不用加 mpt2sas, 看下这个吧，https://github.com/pocopico/rp-ext/issues/123

**Comment by lichangfeng-1** [comment]
谢谢大佬
