### ISSUE TITLE
Custom Request @cdseoo

### ISSUE THREAD

**Issue by wjz304** [wjz304/Redpill_CustomBuild#11]
{"platform":"DS918+", "version":"7.0.1-42218", "jun":"1", "ext":"igb,igbvf,e1000e,e1000,virtio"}

**Comment by cdseoo** [comment]
这个也失败了，可以重开编译吗？

**Comment by cdseoo** [comment]
https://raw.githubusercontent.com/pocopico/rp-ext/master/virtio/rpext-index.json

卡这里了，看来是没有virtio驱动

**Comment by wjz304** [comment]
嗯， 稍等，我注掉 7.0的 virtio

**Comment by cdseoo** [comment]
谢大佬，我重新提交了，virtio没有就算了，主要目标是用igbvf

**Comment by wjz304** [comment]
哦 我看错了，  
![image](https://user-images.githubusercontent.com/5615843/181164526-cdb51b6f-e357-4fe5-a6ce-786baa6f532c.png)
这三个现在都 都会带的

**Comment by cdseoo** [comment]
谢大佬，已经用上了，非常赞的项目

**Comment by wjz304** [comment]
我研究研究换行的问题，这个很多时候 换行看不出来

**Comment by cdseoo** [comment]
启动可以看到dhcp分配了IP，但是pocopico/rp-ext下的igbvf驱动有问题，无法使用，严重丢包。
<img src="https://pic.rmb.bdstatic.com/bjh/d131ea077248333aa941779fecde24a2.png" alt="image.png" title="image.png" />

**Comment by wjz304** [comment]
哪位大佬的好用？ 方便提供下地址，我看看加下可选

**Comment by cdseoo** [comment]
> 哪位大佬的好用？ 方便提供下地址，我看看加下可选

目前还在用以前的梅神版6.2.2，不懂如何提取里面的igbvf.ko
我试试吧

**Comment by wjz304** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/ethernet/intel/igbvf/?h=v5.18.14
这个是源码吧，倒是可以看看自己编
