### ISSUE TITLE
Custom 920 for n5105

### ISSUE THREAD

**Issue by MadGhostcn** [wjz304/Redpill_CustomBuild#12052]
{"platform":"DS920+","version":"7.0.1-42218","maxdisks":"8","maxlanport":"4","internalportcfg":"0xffff","netif_num":"4","vid":"0x1516","pid":"0x8628","ext":"igc,ixgbe","exp":"jumkey","jun":"1"}

**Comment by wjz304** [comment]
为啥你创建的几个都没有触发呢？

**Comment by MadGhostcn** [comment]
> 为啥你创建的几个都没有触发呢？

我也感到很奇怪……
