### ISSUE TITLE
相关工具及帮助

### ISSUE THREAD

**Issue by wjz304** [wjz304/Redpill_CustomBuild#1252]
# Windows 群晖引导解包工具:

2022/09/17:
[brp_win_v0.3b.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9591132/brp_win_v0.3b.zip)
测试版:修复 0.2b 打包 custom.gz 有概率格式错误问题.

2022/09/10:
[brp_win_v0.2b.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9539907/brp_win_v0.2b.zip)
测试版: 支持挂载/卸载 img, 解压/压缩 rd.gz(custom.gz).  压缩/解压 dts(dtb)文件.

2022/09/02:
[brp_win_v0.1b.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9539906/brp_win_v0.1b.zip)
测试版: 支持挂载/卸载 img, 解压 rd.gz(custom.gz). 

----

食用说明：(支持拖拽, 把 img 或者 gz 文件直接拖到对应的bat脚本上就行了)
1. 挂载 img：
`.\mountimg.bat  D:\redpill-xxx.img`

2. 复制出 rd.gz/custom.gz: (假设 1 中被挂载到 x 盘)
`copy x:\rd.gz D:\rd.gz`
`copy x:\custom.gz D:\custom.gz`

3. 卸载 img 的盘: (假设 1 中被挂载到 x 盘)
`.\unmountimg.bat x`

4. 解包 rd.gz/custom.gz
`unpackrd.bat D:\rd.gz`
`unpackrd.bat D:\custom.gz`

4. 打包 rd.gz/custom.gz
`packrd.bat D:\rd.gz`
`packrd.bat D:\custom.gz`

4. 压缩 dts  
`packdts.bat D:\ds920p.dts`

4. 解压 dtb  
`unpackdtb.bat D:\ds920p.dtb`

**Comment by wjz304** [comment]
有关DiskIdxMap、SataPortMap、SasIdxMap三个参数的说明：

摘自https://wp.gxnas.com/10940.html

#在群辉系统中，一个控制器默认只能控制9个硬盘，所以SataPortMap=的数值范围只能是0-9，0则表示屏蔽该控制器，不可以设为SataPortMap=0来隐藏引导盘！

#如果有多个控制器的（每个主板具体有几个控制器，请查阅主板说明书），则SataPortMap=后面的数值有几位就表示有几个控制器。比如SataPortMap=148，表明第一个控制器有1个硬盘，第二个控制器有4个硬盘，第三个控制器有8个硬盘。

#DiskIdxMap=这个参数值，按顺序从左到右每两位数为一个控制器的盘序数值，这两位数为16进制数，如果数值小于等于9或者大于10的，需要在数值前面加个0。比如DiskIdxMap=000105的意思是，第一个控制器的磁盘（引导盘）从序号1（00为序列1）开始往后排，第二个控制器的4个硬盘从序号2（01为序号2）开始往后排，第三个驱动器的8个硬盘从序号5（05为序号6）开始往后排。此时在群晖DSM7.X的系统里面看到磁盘序号就会从磁盘1（引导盘）到磁盘13。

#这里有个小技巧，可以将控制器的盘序设置超过当前最大磁盘数量。例如我想把第1个控制器的引导盘隐藏，可以改成DiskIdxMap=0C0004，引导盘在群晖系统里面就看不到了，此时在群晖DSM7.X的系统里面看到磁盘序号就会从磁盘1到磁盘12（引导盘被隐藏了），同时还治愈了很多患有强迫症的童鞋！

#SasIdxMap为SAS硬盘的个数，默认使用SATA硬盘的时候设置为0。

**Comment by wjz304** [comment]
矿神群晖SPK套件中心
https://imnks.com/1780.html

**Comment by maxage** [comment]
225驱动有吗？

**Comment by wjz304** [comment]
> 225驱动有吗？

igc

**Comment by wjz304** [comment]
arpl下载pat慢的解决办法:
<pre>
sed -i 's/global.download.synology.com/cndl.synology.cn/g' /opt/arpl/menu.sh
sed -i 's/global.download.synology.com/cndl.synology.cn/g' `find /opt/arpl/model-configs/ -type f -name '*.yml'`
</pre>
arpl更新慢的解决办法:
<pre>
sed -i 's|https://github.com|https://ghproxy.com/https://github.com|g' /opt/arpl/menu.sh
</pre>
arpl下获取网卡驱动:
<pre>
for i in `ls /sys/class/net | grep -v 'lo'`; do echo $i -- `ethtool -i $i | grep driver`; done
</pre>
Nvidia卡驱动：
<pre>
https://imnks.com/7009.html
</pre>
i915.ko核显驱动：
<pre>
https://imnks.com/6421.html
</pre>

**Comment by weng5040** [comment]
求大佬帮忙看下   x520-SDR引导后一直获取不到IP  只识别到主板网卡 安装好群晖系统后也无法识别网卡
这些是最近几天编译的 都识别不了网卡
{"model":"DS918+","version":"7.2.0-64551","jun":"1","lkm":"test","maxlanport":"7","internalportcfg":"0xffff","netif_num":"3","vid":"0x0781","pid":"0x5571","diskidxmap":"0004","sataportmap":"46","addons":"acpid2,boot-wait,misc","modules":"e1000e,ixgb,ixgbe,igb,igbvf,igc,ixgbevf,e1000"}

{"model":"DS918+","version":"7.2.0-64551","jun":"1","lkm":"test","maxlanport":"7","internalportcfg":"0xffff","netif_num":"3","vid":"0x0781","pid":"0x5571","diskidxmap":"0004","sataportmap":"46","addons":"boot-wait,misc,acpid2","modules":"e1000e,ixgbe"}

{"platform":"DS918+","version":"7.2.0-64551","internalportcfg":"0xffff","netif_num":"3","vid":"0x23A9","pid":"0xEF18","diskidxmap":"0004","sataportmap":"46","sasidxmap":"0","ext":"ixgbe,e1000e","exp":"pocopico","jun":"0","dev":"1"}

{"model":"DS918+","version":"7.2.0-64551","jun":"1","lkm":"test","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5571","diskidxmap":"0004","sataportmap":"46","addons":"boot-wait,misc,acpid2","modules":"ixgbe"}

这个是去年编译的可以识别到网卡的引导
{"platform":"DS918+","version":"7.1.1-42962","internalportcfg":"0xffff","netif_num":"3","vid":"0x23A9","pid":"0xEF18","diskidxmap":"0004","sataportmap":"46","sasidxmap":"0","ext":"ixgbe,igb","exp":"pocopico","jun":"0","dev":"1"}
