### ISSUE TITLE
Custom Coolmaster920

### ISSUE THREAD

**Issue by yokor** [wjz304/Redpill_CustomBuild#12888]
{"platform":"DS920+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x05e3","pid":"0x0743","ext":"r8168","exp":"pocopico","jun":"0","dev":"1"}

**Comment by yokor** [comment]
thx 4 ur help!

**Comment by wjz304** [comment]
No worries.
