### ISSUE TITLE
Custom 918 memo

### ISSUE THREAD

**Issue by buhonghao** [wjz304/Redpill_CustomBuild#13]
{"platform":"DS918+", "version":"7.0.1-42218", "sataportmap":"116", "diskidxmap":"100001", "jun":"1", "ext":"vmxnet3,igb,igbvf,e1000e,e1000,virtio,r8125,r8168,tg3"}

**Comment by wjz304** [comment]
不要 加 virtio，virtio不在  https://raw.githubusercontent.com/pocopico/rp-ext/main/exts 里

**Comment by wjz304** [comment]
默认 virtio 都会带的

**Comment by buhonghao** [comment]
需要重新开一个吗？

**Comment by wjz304** [comment]
嗯，新建一下吧
