### ISSUE TITLE
Custom 3622xs 7.1.1 pocopico

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#1342]
{
"platform": "DS3622xs+",
"version": "7.1.1-42951",
"map": "46, 0004",
"usb": "0x6544, 0x0930",
"jun": "0",
"exp": "pocopico",
"ext": "r8125, e1000, e1000e, vmxnet3,mpt3sas,ixgbe,ixgbevf,igb,igbvf"
}

**Comment by wjz304** [comment]
transfer

**Comment by wjz304** [comment]
我下载没啥问题啊，你啥浏览器？

**Comment by wjz304** [comment]
试下 快传 吧

**Comment by lichangfeng-1** [comment]
可能是当时网络有问题，我今天下载就能解压出来了，
