### ISSUE TITLE
Custom 918 memopo

### ISSUE THREAD

**Issue by buhonghao** [wjz304/Redpill_CustomBuild#14]
{"platform":"DS918+", "version":"7.0.1-42218", "sataportmap":"116", "diskidxmap":"100001", "jun":"1", "ext":"vmxnet3,igb,igbvf,e1000e,e1000,r8125,r8168,tg3"}

**Comment by buhonghao** [comment]
谢谢

**Comment by wjz304** [comment]
有问题及时联系，我尽力解决
