### ISSUE TITLE
Custom UNAS 401P

### ISSUE THREAD

**Issue by wxlxp** [wjz304/Redpill_CustomBuild#14918]
{"platform":"DS920+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0xABCD","pid":"0x1234","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/10055841/ds920p.zip","ext":"r8125,r8152,e1000,e1000e,igb","exp":"pocopico","jun":"0"}

**Comment by wxlxp** [comment]
delete builds

**Comment by chenxudong2020** [comment]
401p四个盘都能正常识别码
