### ISSUE TITLE
Custom DS918

### ISSUE THREAD

**Issue by onlypeng** [wjz304/Redpill_CustomBuild#15]
{"platform":"DS918+", "version":"7.1.0-42661", "mac":"00:e2:69:54:d3:aa", "ext":"r8125"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/181210217-a84ee7e0-5bce-44a5-ad27-317a983aad4e.png)
这个mac 确实欠考虑了，我修复一下

**Comment by onlypeng** [comment]
我也没想到つ﹏⊂

**Comment by wjz304** [comment]
改好了， 加了自动去 “:”， 有没有都可以识别了

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/181212360-bc3b8639-6f7e-439e-9650-18e87853652c.png)

**Comment by onlypeng** [comment]
就写了一个mac地址，生成完后引导配置文件中存在第二个mac
