### ISSUE TITLE
Custom 2022-09-06 LCmnks

### ISSUE THREAD

**Issue by liuchanghy** [wjz304/Redpill_CustomBuild#1500]
{"platform":"DS918+","version":"7.1.0-42661","map":"6,00","sn":"1980PDN002189","mac":"001132888A93, 001132888A94, 001132888A95, 001132888A96, 001132888A97, 001132888A98","usb":"0x5571, 0x0781","ext":"e1000,e1000e,igb,ixgbe,r8125,r8152,vmxnet3","exp":"pocopico","jun":"0"}

**Comment by liuchanghy** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds
