### ISSUE TITLE
custom 918

### ISSUE THREAD

**Issue by liangfeng8515** [wjz304/Redpill_CustomBuild#153]
{
"platform":"DS918+", 
"version":"7.1.0-42661", 
"ext":"r8168,r8169",
"exp":"pocopico"
}

**Comment by liangfeng8515** [comment]
{
"platform":"DS918+",
"version":"7.1.0-42661",
"sn":"1980PDN002189", 
"mac":"001132888A95",
"ext":"r8168",
"exp":"pocopico",
}

**Comment by wjz304** [comment]
【👉[json错误检测](https://json-online.com/check/)】  主页有错误检测的网址

**Comment by liangfeng8515** [comment]
{
"platform":"DS918+",
"version":"7.1.0-42661",
"sn":"1980PDN002189",
"mac":"001132888A95",
"ext":"r8168",
"exp":"pocopico"
}
