### ISSUE TITLE
Custom DS920 forVM

### ISSUE THREAD

**Issue by 1900forever** [wjz304/Redpill_CustomBuild#1654]
{"platform":"DS920+","version":"7.1.1-42951","map":"1, 00","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip","usb":"0x0001, 0x46f4","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
由于 pocopico 大的 rp-ext 新增的 eudev 修改json格式，导致 exts获取报错，2022-09-09 10:03:40 之后的issues，我会触发重新编译.
