### ISSUE TITLE
Custom Redpill_CustomBuild_20221208

### ISSUE THREAD

**Issue by shuchangbing** [wjz304/Redpill_CustomBuild#17061]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
