### ISSUE TITLE
Custom 2022-12-09

### ISSUE THREAD

**Issue by qiliye** [wjz304/Redpill_CustomBuild#17154]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x090c","pid":"0x2000","ext":"igc","dev":"1"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
