### ISSUE TITLE
Custom 4021-1

### ISSUE THREAD

**Issue by esacmsn** [wjz304/Redpill_CustomBuild#17166]
{"repository":"pocopico_jun","platform":"RS4021xs+","version":"7.0.1-42218","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","ext":"e1000e"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/13
