### ISSUE TITLE
Custom 918 

### ISSUE THREAD

**Issue by Suer2022** [wjz304/Redpill_CustomBuild#17298]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"8","vid":"0x46f4","pid":"0x0001","ext":"igc"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
