### ISSUE TITLE
Custom Sonic 7.1

### ISSUE THREAD

**Issue by questsonic** [wjz304/Redpill_CustomBuild#17475]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x1320","pid":"0x1908","ext":"r8125","dev":"1"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
