### ISSUE TITLE
Custom 3622-42962

### ISSUE THREAD

**Issue by lucifer-chou** [wjz304/Redpill_CustomBuild#17505]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","ext":"r8168","dev":"1"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
