### ISSUE TITLE
Custom 2022-12-12

### ISSUE THREAD

**Issue by donyang90** [wjz304/Redpill_CustomBuild#17540]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxdisks":"4","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
