### ISSUE TITLE
Custom NAS

### ISSUE THREAD

**Issue by stardaniel5216** [wjz304/Redpill_CustomBuild#17682]
{"repository":"pocopico_develop","platform":"DS1520+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5571","ext":"igc"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/12
