### ISSUE TITLE
Custom junNAS

### ISSUE THREAD

**Issue by jun126jun** [wjz304/Redpill_CustomBuild#18286]
{"repository":"pocopico_develop","platform":"DS920+","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","ext":"vmxnet3,-virtio,r8125,r8169","dev":"1"}

**Comment by wjz304** [comment]
pocopico_develop&pocopico_jun 现在非dev模式全型号编不过，且该错误在下游无法容错，我已经PR了，非要用pocopico暂时用 dev模式吧。
