### ISSUE TITLE
Custom GEN8-3615

### ISSUE THREAD

**Issue by zhaoyy008** [wjz304/Redpill_CustomBuild#18352]
{"repository":"pocopico_develop","platform":"DS3615xs","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x346d","pid":"0x5678","diskidxmap":"00","sataportmap":"6","ext":"tg3"}

**Comment by wjz304** [comment]
pocopico commit 575abe6c6ac4e4c8cbd640924d40d965016a6385
