### ISSUE TITLE
Custom datiantianNAS

### ISSUE THREAD

**Issue by tiantuzhi** [wjz304/Redpill_CustomBuild#18387]
{"repository":"pocopico_develop","platform":"DVA3221","version":"7.1.1-42962","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","ext":"vmxnet3,e1000e"}

**Comment by wjz304** [comment]
pocopico commit 575abe6c6ac4e4c8cbd640924d40d965016a6385
