### ISSUE TITLE
Custom DSM918_7.1.1 _42962

### ISSUE THREAD

**Issue by phong567588** [wjz304/Redpill_CustomBuild#1900]
{"platform":"DS918+","version":"7.1.1-42962","map":"6,00","usb":"0x0001, 0x46f4","ext":"r8169,r8168","exp":"pocopico","jun":"1","dev":"1"}

**Comment by phong567588** [comment]
delete builds

**Comment by wjz304** [comment]
DS918+/DS920+/DS1621+/DVA1622 的 7.1.1 版本要用(dev)模式.
