### ISSUE TITLE
Custom ts551

### ISSUE THREAD

**Issue by yancheng86** [wjz304/Redpill_CustomBuild#19127]
{"repository":"pocopico_develop","platform":"DS918+","version":"7.0.1-42218","lkm":"redpill","maxdisks":"9","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5583","diskidxmap":"000C18","sataportmap":"21212","sasidxmap":"0","ext":"igc"}

**Comment by jinpei-chen** [comment]
你的引导成功安装吗？
