### ISSUE TITLE
Custom iota 

### ISSUE THREAD

**Issue by gundamf6** [wjz304/Redpill_CustomBuild#195]
{"platform":"DS3615xs","version":"7.0.1-42218","map":"00,2","dtb":"","sn":"1230LWN015198,1230LWN015199","mac":"0011328C41D4,0011328C41D4","usb":"0x0727, 0x05e3","ext":"","exp":"jumkey","jun":"0"}

**Comment by wjz304** [comment]
不能设置两个sn

**Comment by gundamf6** [comment]
> 不能设置两个sn

没注意，我还以为一个SN对应一个MAC

**Comment by gundamf6** [comment]
> 不能设置两个sn

大佬，假如想要自定义user_config.json 应该在哪设置？
