### ISSUE TITLE
Custom_Glen_920_For_HS_401P

### ISSUE THREAD

**Issue by glenlgd** [wjz304/Redpill_CustomBuild#19942]
{"repository":"pocopico_jun","platform":"DS920+","version":"7.1.0-42661","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5591","ext":"-dtb,dtbpatch","dev":"1"}

**Comment by chenxudong2020** [comment]
四个盘都能正常识别码
