### ISSUE TITLE
Custom 万由401p_DS920_7.1.1 42962

### ISSUE THREAD

**Issue by chenxudong2020** [wjz304/Redpill_CustomBuild#20079]
{"repository":"PeterSuh-Q3_master","platform":"DS920+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x090C","pid":"0x2000","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/10328374/ds920p_401p.zip","ext":"https://raw.githubusercontent.com/chenxudong2020/synology-r8125/main/r8125/rpext-index.json,r8152","exp":"jumkey","jun":"0"}

**Comment by wjz304** [comment]
https://github.com/chenxudong2020/synology-r8125/blob/main/r8125/rpext-index.json
大兄弟，这里的链接指向没改啊
