### ISSUE TITLE
Custom 3221-42218-1

### ISSUE THREAD

**Issue by sephchiu** [wjz304/Redpill_CustomBuild#20108]
{"repository":"pocopico_develop","platform":"DVA3221","version":"7.0.1-42218","lkm":"redpill","maxdisks":"48","maxlanport":"7","internalportcfg":"0xffff","netif_num":"1","vid":"0x154b","pid":"0x6002","diskidxmap":"00","sataportmap":"99","sasidxmap":"0","ext":"r8168,mpt3sas"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/14
