### ISSUE TITLE
Custom 401

### ISSUE THREAD

**Issue by drmrc** [wjz304/Redpill_CustomBuild#20785]
{"repository":"pocopico_jun","platform":"DS918+","version":"7.1.0-42661","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x090c","pid":"0x2000","diskidxmap":"0002","sataportmap":"22","ext":"r8125,r8152,r8168,r8169"}

**Comment by wjz304** [comment]
报错不影响编译结果
