### ISSUE TITLE
Custom 3221

### ISSUE THREAD

**Issue by zz0770** [wjz304/Redpill_CustomBuild#20971]
{"repository":"pocopico_develop","platform":"DVA3221","version":"7.0.1-42218","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","diskidxmap":"00","sataportmap":"4","sasidxmap":"0","ext":"igb","dev":"1"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/14
