### ISSUE TITLE
Custom DVA3221_ZWZW

### ISSUE THREAD

**Issue by ai773203918** [wjz304/Redpill_CustomBuild#21071]
{"repository":"pocopico_develop","platform":"DVA3221","version":"7.0.1-42218","lkm":"redpill","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x058F","pid":"0x6387","diskidxmap":"0400","sataportmap":"24","sasidxmap":"0"}

**Comment by wjz304** [comment]
https://github.com/pocopico/redpill-load/pull/14
