### ISSUE TITLE
Custom ruoer

### ISSUE THREAD

**Issue by Ruoer-Y** [wjz304/Redpill_CustomBuild#2168]
{"platform":"DS920+","version":"7.1.1-42962","map":"0,00","usb":"0x0001, 0x46f4","ext":"r8152,r8168,r8169,mptsas,mpt3sas,r8125,igb,e1000e,e1000,vmxnet3,vmw_pvscsi,megaraid_sas","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
delete builds
