### ISSUE TITLE
Custom 920 ruoer

### ISSUE THREAD

**Issue by Ruoer-Y** [wjz304/Redpill_CustomBuild#2203]
{"platform":"DS920+","version":"7.1.1-42962","map":"22,0002","mac":"0011235B0CD5","usb":"0x0001, 0x46f4","ext":"r8125,vmxnet3,e1000,e1000e,megaraid_sas,mpt3sas","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
delete builds
