### ISSUE TITLE
Custom qaz

### ISSUE THREAD

**Issue by Ruoer-Y** [wjz304/Redpill_CustomBuild#2228]
{"platform":"DS920+","version":"7.1.1-42962","map":"22,0002","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/9235785.zip","usb":"0x0001, 0x46f4","ext":"megaraid_sas,mpt3sas,mptsas,r8125,vmxnet3","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
delete builds
