### ISSUE TITLE
Custom20230226010827

### ISSUE THREAD

**Issue by dptr** [wjz304/Redpill_CustomBuild#24874]
{
"repository": "pocopico_develop",
"platform": "DS918+",
"version": "7.1.1-42962",
"lkm": "dev",
"maxlanport": "7",
"internalportcfg": "0x03",
"esataportcfg": "0xfffc",
"netif_num": "1",
"vid": "0x30de",
"pid": "0x6545",
"diskidxmap": "0002",
"sataportmap": "24",
"exts": "redpill-misc,thethorgroup.virtio,jumkey.acpid2,igb"
}

**Comment by wjz304** [comment]
明天吧，还在改
