### ISSUE TITLE
Custom 2022-09-11

### ISSUE THREAD

**Issue by KSOYU** [wjz304/Redpill_CustomBuild#2574]
{"platform":"DS918+","version":"6.2.4-25556","map":"2,00","mac":"001132123456","usb":"0x1000, 0x090C","ext":"-virtio,-acpid2,-misc,3w-sas,8139cp,8139too,aacraid,aic94xx,alx,arcmsr,asix,atl1,atl1c,atl1e,atl2,atlantic,ax88179_178a,be2net,hpsa,mvsas,tg3,tcrp-diag,mptspi,sky2,mptsas,skge,sfc,mpt3sas,early-telnet,e1000e,mpt2sas,e1000,mlx5_core,dtb-patch,mlx4_core,dm9601,cxgb4vf,megaraid_sas,ixgbevf,cxgb4,cxgb3,ixgbe,igbvf,cxgb,bnx2x,bnx2,bna,i40e,igb,qlcnic,r8101,r8125,r8152,r8168,r8169,raspbi-pill,rtl8150,vxge,vmxnet3,vmw_pvscsi,via-velocity,via-rhine,v9fs,tn40xx","exp":"jumkey","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
Failed to dump extension pocopico.sfc for platform ds918p_25556 as its recipe file cannot be retrieved.
