### ISSUE TITLE
Custom custom 3615

### ISSUE THREAD

**Issue by gundamf6** [wjz304/Redpill_CustomBuild#270]
{"platform":"DS3615xs","version":"7.0.1-42218","map":"2,00","sn":"1230LWN015198","mac":"0011328C41D4,0011328C41D5","usb":"0x0727, 0x05e3","ext":"rtl8150,e1000e,e1000","exp":"jumkey","jun":"0"}

**Comment by wjz304** [comment]
map 反了

**Comment by wjz304** [comment]
rtl8150 ds3615xs_42218.json 的 sha256 不正确，已给 pocopico 提bug
