### ISSUE TITLE
Custom dd920  20220912

### ISSUE THREAD

**Issue by yanfeinet** [wjz304/Redpill_CustomBuild#2721]
{"platform":"DS920+","version":"7.0.1-42218","dtb":"http://yanfeinet.cn:8840/ds1621p.dts","usb":"0x0001, 0x46f4","ext":"e1000e,igb,ixgbe,r8125,r8168,vmxnet3","exp":"jumkey","jun":"1"}

**Comment by wjz304** [comment]
ds1621p.dts:179.7-181.1   文件 179-181行 有错误
