### ISSUE TITLE
Custom 2022-09-12-12

### ISSUE THREAD

**Issue by Rookiewan** [wjz304/Redpill_CustomBuild#2756]
{"platform":"DS918+","version":"7.0.1-42218","usb":"0x5591, 0x0781","ext":"3w-sas,8139cp,8139too,aacraid,aic94xx,alx,arcmsr,asix,atl1,atl1c,atl1e,atl2,atlantic,ax88179_178a,be2net,hpsa,hv_netvsc,forcedeth,early-telnet,e1000e,e1000,dtb-patch,dm9601,cxgb4vf,cxgb4,cxgb3,cxgb,bnx2x,bnx2,bna,i40e,iavf,igb,igbvf,ixgbe,ixgbevf,megaraid_sas,mlx4_core,mlx5_core,mpt2sas,mpt3sas,mptsas,mptspi,mvsas,nct6775,tg3,tcrp-diag,sky2,skge,sfc,sata_nv,rtl8150,raspbi-pill,r8169,r8168,r8152,r8125,r8101,qlcnic,qla2xxx,tn40xx,v9fs,via-rhine,via-velocity,vmw_pvscsi,vmxnet3,vxge,wch","exp":"jumkey","jun":"1","dev":"1"}

**Comment by wjz304** [comment]
v9fs 有问题，编不过

**Comment by wjz304** [comment]
另外 扩展太多也编不过
