### ISSUE TITLE
Custom forpve

### ISSUE THREAD

**Issue by wxjiyc** [wjz304/Redpill_CustomBuild#27898]
{"repository":"pocopico_develop","model":"SA6400","version":"7.2.0-64216","lkm":"dev","maxdisks":"1","maxlanport":"1","internalportcfg":"0x1","netif_num":"1","vid":"0x46f4","pid":"0x0001","addons":"cpuinfo,dtbpatch,misc","modules":"acpi-cpufreq,virtio,virtio_blk,virtio_input,virtio_mmio,virtio_net,virtio_pci,virtio_ring,virtio_scsi,vmw_pvscsi"}

**Comment by hiwjy** [comment]
delete builds
