### ISSUE TITLE
Custom DS918 7.1

### ISSUE THREAD

**Issue by youngnet** [wjz304/Redpill_CustomBuild#2805]
{"platform":"DS918+","version":"7.1.1-42962","map":"1,00","usb":"0x0001, 0x46f4","ext":"e1000e,igb,ixgbe,e1000","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
DS918+/DS920+/DS1621+/DVA1622 的 7.1.1 版本要用(dev)模式.
