### ISSUE TITLE
生成镜像不能正常启动

### ISSUE THREAD

**Issue by nbwgl** [wjz304/Redpill_CustomBuild#30944]
在这个平台上生成的镜像，我怎么每次启动都只是到start信息，后面就没有了。看网卡mac也没有获取到ip地址。应该是没有启动完成。
![image](https://user-images.githubusercontent.com/10443696/231936800-9fcf6915-5f6d-4899-bc1a-d2180f46afd1.png)

**Comment by nbwgl** [comment]
已经选择不同方式生成多个版本，还是不行

**Comment by nbwgl** [comment]
希望能够解决这个问题，我主要是想集成几个网卡的驱动，可以在esxi主机上直通网卡，是bcom5720网卡，用tg3驱动，感谢！

**Comment by wjz304** [comment]
试一试吧

**Comment by nbwgl** [comment]
![image](https://user-images.githubusercontent.com/10443696/233566838-617fa885-f0fa-4ffe-823c-cd91c404f767.png)
新创建了一个，还是启动不了，我哪里做错了吗？
https://github.com/wjz304/Redpill_CustomBuild/issues/31397

**Comment by wjz304** [comment]
> ![image](https://user-images.githubusercontent.com/10443696/233566838-617fa885-f0fa-4ffe-823c-cd91c404f767.png) 新创建了一个，还是启动不了，我哪里做错了吗？ #31397

1. 建议先看线说明。
2. jun模式就显示这些。
