### ISSUE TITLE
Custom Build2022-09-13fyf

### ISSUE THREAD

**Issue by Yang002Www** [wjz304/Redpill_CustomBuild#3100]
{"platform":"DS3622xs+","version":"7.1.0-42661","usb":"0x0001, 0x46f4","ext":"e1000,e1000e,megaraid_sas,mlx4_core,rtl8150,r8152,cxgb","exp":"jumkey","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
title 要 英文

**Comment by wjz304** [comment]
jumkey 不支持 710
