### ISSUE TITLE
DS923 编译正常，上机测试失败，任何网卡失联

### ISSUE THREAD

**Issue by Yanajnp** [wjz304/Redpill_CustomBuild#31942]
{"model":"DS923+","version":"7.2.0-64216","jun":"1","lkm":"dev","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5571","addons":"acpid2,boot-wait,cpuinfo,dtbpatch,misc","modules":"e1000e,e1000,igb,r8125,r8168,r8169,virtio_net,vmxnet3"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/234316869-fe6024f3-6a77-4df2-ae8c-5d7197646996.png)
实测 至少e1000 和 vmxnet3兼容
