### ISSUE TITLE
Custom dell 730xd 3622xs 7.01 jun

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#3414]
{
"info": "任何不读注意事项就创建的行为都是耍流氓!",
"platform": "DS3622xs+",
"version": "7.0.1-42218",
"map": "46, 0004",
"usb": "0x6544, 0x0930",
"jun": "1",
"exp": "pocopico",
"ext": "r8125, e1000, e1000e, vmxnet3,mpt3sas,ixgbe,ixgbevf,igb,igbvf,aacraid"
}

**Comment by lichangfeng-1** [comment]
transfer

**Comment by lichangfeng-1** [comment]
@wjz304  大佬，我这个驱动好像一个都没生效，帮我看看吧，服务器是戴尔730xd，cpu是2路E5 2650v4,网卡是x540+i350，阵列卡是H330直通模式，我查到是PERC H330 Mini (嵌入式)，芯片应该LSI 3008的。但是现在网卡都不能识别，我用之前8月29号之前的能识别网卡，不能识别阵列卡硬盘

**Comment by wjz304** [comment]
其实各种硬件方面我也不了解，只是这些扩展之间有些有冲突，你之前的能识别网卡的是哪一个？ 我看看有啥

**Comment by lichangfeng-1** [comment]
就是这个，从“https://wp.gxnas.com/11849.html/comment-page-9”博客下载的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Redpill_CustomBuild"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月15日(星期四) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjz304/Redpill_CustomBuild] Custom dell 730xd 3622xs 7.01 jun (Issue #3414)





 
其实各种硬件方面我也不了解，只是这些扩展之间有些有冲突，你之前的能识别网卡的是哪一个？ 我看看有啥
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

DS3622xs_7.X引导文件（支持7.0.1-42218到7.1.1-42962）.img (128.00M, 2022年10月15日 14:43 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0c396436356161cb04b3411b1361531c59080503070202574c0c02030c4c55045908490e5158561e505f575357520552020c545735596177320a52040719126c56173ce4c8d4ddfda5859a959db7c680b70e4a061b504c07530b550e80dc561d5017551b01535805539acd185c0c06335c&code=a9d65aa3

**Comment by lichangfeng-1** [comment]
https://wp.gxnas.com/11849.html/comment-page-9

**Comment by lichangfeng-1** [comment]
https://dl.gxnas.com:1443/黑群晖/黑群晖DSM6.24和DSM7.x测试版/DS3622xs_7.X引导文件（支持7.0.1-42218到7.1.1-42962）.img

**Comment by lichangfeng-1** [comment]
@wjz304

**Comment by wjz304** [comment]
置顶的 issue 有工具可以解包

**Comment by lichangfeng-1** [comment]
解包以后可以直接添加阵列卡驱动进去不





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wjz304/Redpill_CustomBuild] Custom dell 730xd 3622xs 7.01 jun (Issue #3414)





 
置顶的 issue 有工具可以解包

**Comment by wjz304** [comment]
理论上是可以的，不过要改那个 sh脚本，另外打包我没有测试过，也没人给我反馈.... 你可以试试

**Comment by wjz304** [comment]
我在下载了，一会儿我也解包看看

**Comment by lichangfeng-1** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wjz304/Redpill_CustomBuild] Custom dell 730xd 3622xs 7.01 jun (Issue #3414)





 
我在下载了，一会儿我也解包看看
 
&mdash;

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/190338378-f92adb10-673f-4d07-8425-46c2acd25a04.png)

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/190338986-e51fcfb9-9d6e-438c-9b74-5ca42242b5ef.png)

**Comment by wjz304** [comment]
貌似 igb 就够了

**Comment by wjz304** [comment]
https://blog.csdn.net/ytlzq0228/article/details/117448983

**Comment by lichangfeng-1** [comment]
我这个阵列卡已经是HBA模式了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wjz304/Redpill_CustomBuild] Custom dell 730xd 3622xs 7.01 jun (Issue #3414)





 
https://blog.csdn.net/ytlzq0228/article/details/117448983

**Comment by wjz304** [comment]
这我真的就不清楚了，试试其他型号？

**Comment by lichangfeng-1** [comment]
@wjz304  这个服务器的网卡上有4个口两个网卡芯片分别是x540和i350，应该是igb和ixgbe

**Comment by lichangfeng-1** [comment]
igb好像不含x540的驱动哇，igb有i350的驱动我是知道的、另外是不是LSI阵列卡驱动和戴尔的阵列卡驱动冲突了，我看到戴尔的阵列卡好像是有单独的一个驱动。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wjz304/Redpill_CustomBuild] Custom dell 730xd 3622xs 7.01 jun (Issue #3414)





 
貌似 igb 就够了
