### ISSUE TITLE
Custom 2022-09-16 3617xs dell730xd 540 350 H330

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#3732]
{"platform":"DS3617xs","version":"7.0.1-42218","map":"46,0004","usb":"0x6544, 0x0930","ext":"e1000e,tg3,igb,ixgbe,aacraid,mpt3sas,mpt2sas,r8125,rtl8150","exp":"jumkey","jun":"1","dev":"1"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/190621333-e2ac8b39-c5b3-4b8e-b252-393c6198e4cf.png)

**Comment by lichangfeng-1** [comment]
@wjz304 大佬我这个构建是哪儿出错了哇
