### ISSUE TITLE
Custom NASboot

### ISSUE THREAD

**Issue by lygttl** [wjz304/Redpill_CustomBuild#3738]
{"platform":"DS918+","version":"7.1.1-42962","map":"4,00","usb":"0x5571, 0x0781","ext":"8139too,8139cp,r8169,r8168,r8152,r8125,rtl8150,be2net,r8101,tg3","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/190621186-cacba159-40c1-4876-8941-5d3709b74146.png)
