### ISSUE TITLE
关于PID和VID设置后，固件内PID数值变成跟VID一致，PID设置无效。

### ISSUE THREAD

**Issue by Swiftfrog** [wjz304/Redpill_CustomBuild#3945]
之前具体设置和实际的user_config.json 如下：

{"platform":"DS918+","version":"7.1.1-42962","maxlanport":"2","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5571","diskidxmap":"0006","sataportmap":"64","sasidxmap":"0","ext":"ixgbe","exp":"pocopico","jun":"0"}

https://github.com/wjz304/Redpill_CustomBuild/actions/runs/3072821689

{
    "extra_cmdline": {
        "pid": "0x0781",
        "vid": "0x0781",
        "sn": "1790PDN016252",
        "mac1": "00113256B8F6",
        "mac2": "00113256B8F7",
        "netif_num": 2,
        "DiskIdxMap": "0006",
        "SataPortMap": "64",
        "SasIdxMap": "0"
    },
    "synoinfo": {
        "internalportcfg": "0xffff",
        "maxlanport": "2"
    },
    "ramdisk_copy": {}
}

**Comment by wjz304** [comment]
修复了
