### ISSUE TITLE
Custom all

### ISSUE THREAD

**Issue by qqxufeng** [wjz304/Redpill_CustomBuild#4004]
{"platform":"DS918+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0951","pid":"0x1666","ext":"-virtio,-acpid2,-misc,3w-sas,8139cp,8139too,aacraid,aic94xx,alx,asix,atl1,atl1c,atl1e,atl2,atlantic,ax88179_178a,be2net,bna,igbvf,igb,iavf,i40e,hpsa,forcedeth,e1000e,e1000,dm9601,cxgb4vf,cxgb4,cxgb3,cxgb,bnx2x,bnx2,ixgbe,ixgbevf,megaraid_sas,mlx4_core,mpt2sas,mpt3sas,mptsas,mptspi,qla2xxx,qlcnic,r8101,r8125,r8152,r8168,r8169,wch,vxge,vmxnet3,vmw_pvscsi,via-velocity,via-rhine,v9fs,tn40xx,tg3,sky2,skge,sfc,rtl8150","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
DS918+ 全驱动编不过，即使修复大部分的 sha256也不行，v9fs 有问题
