### ISSUE TITLE
Custom DS918 all

### ISSUE THREAD

**Issue by HuanghaiD** [wjz304/Redpill_CustomBuild#4115]
{"platform":"DS918+","version":"7.1.1-42962","maxdisks":"32","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","diskidxmap":"00","sataportmap":"8","sasidxmap":"0","ext":"3w-sas,8139cp,atl1,atl2,atlantic,ax88179_178a,igbvf,igb,i40e,iavf,e1000e,e1000,ixgbe,ixgbevf,rtl8150,sfc,skge,tn40xx,tg3,sky2,v9fs,vmw_pvscsi,vmxnet3,vxge,wch,r8169,r8168,r8152,r8125,r8101,qlcnic,qla2xxx,mptspi,mptsas,mpt3sas,mpt2sas,mlx4_core,megaraid_sas,bnx2,bnx2x,cxgb,cxgb3,8139too,aacraid,cxgb4,cxgb4vf,aic94xx,alx,dm9601,asix,atl1c,atl1e,forcedeth,hpsa,be2net,bna","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
参考 https://github.com/wjz304/Redpill_CustomBuild/issues/1002
