### ISSUE TITLE
Custom qpxf

### ISSUE THREAD

**Issue by shenlian102** [wjz304/Redpill_CustomBuild#4176]
{"platform":"DS3622xs+","version":"7.1.1-42962","maxdisks":"7","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x1976","pid":"0x1307","ext":"rtl8150,r8152,r8125","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/190893921-cc378e62-78ea-45ba-bc4e-33fff5662c22.png)
