### ISSUE TITLE
Custom nas

### ISSUE THREAD

**Issue by RideWindOne** [wjz304/Redpill_CustomBuild#422]
{"platform":"DS920+","version":"7.0.1-42218","dtb":"https://github.com/RideWindOne/redpill-load/raw/master/redpill-dtb/releases/ds920p.zip","usb":"0x0001, 0x46f4","ext":"ixgbe,ixgbevf,r8125,r8168,igb,tg3","exp":"jumkey","jun":"1"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/184521974-37e38458-7167-4aa8-b00c-3cbbc4d01f6c.png)
