### ISSUE TITLE
virtio驱动问题

### ISSUE THREAD

**Issue by zczc0417** [wjz304/Redpill_CustomBuild#4357]
DVA3221  KVM虚拟机virtio驱动应该有问题，virtio高性能网卡找不到DSM，E1000网卡找不到硬盘

**Comment by wjz304** [comment]
DVA3221 没有 virtio 驱动, (编译结果附件压缩包里有 exts.txt 会显示集成的驱动)

**Comment by wjz304** [comment]
v9fs 包含 virtio,  试下
