### ISSUE TITLE
DS920+求助。

### ISSUE THREAD

**Issue by RideWindOne** [wjz304/Redpill_CustomBuild#439]
前天自己用本地机器 编译的DS920+都能正常启动。。。然后不小心删错了文件。。。
现在不管是在线action编译的还是自己机器编译的统统找不到IP。但是DS920+使用正常。
处理器J4125,D-1581,E-2176M这三个之前都能启动。现在死活找不到IP，不知道是什么原因。。

**Comment by wjz304** [comment]
首次启动慢，多等一会看看

**Comment by RideWindOne** [comment]
等了一夜也找不到IP。感觉是不是源码改了。。。

**Comment by wjz304** [comment]
本地用 [tinycore-redpill](https://github.com/pocopico/tinycore-redpill) 吗?,  920+ 正常是指？

**Comment by RideWindOne** [comment]
前天编译的用的jumkey的源码。正常是指都可以在2分钟内找到IP并且正常安装。

**Comment by wjz304** [comment]
jumkey 的库 一个月没有变动过了，而且3个机器都找不到ip有点...

**Comment by wjz304** [comment]
我只能帮忙看看，你加我qq吧，这有点费劲，304403268

**Comment by RideWindOne** [comment]
但是驱动pocopico显示三天前有更新，也没看到变了啥。。。
这是用你的action构建的，一样启动不了。。。
https://github.com/wjz304/Redpill_CustomBuild/actions/runs/2854238757

**Comment by RideWindOne** [comment]
换了种方法，找到别人以前用你的机器 人编译的版本，替换自己的custum.gz。可以正常启动。

**Comment by wjz304** [comment]
确实没啥变化，只是增加了 7.1.1，
jumkey 的 jun模式吗？

**Comment by wjz304** [comment]
base 是哪个？

**Comment by RideWindOne** [comment]
https://github.com/wjz304/Redpill_CustomBuild/issues/83下载的这个里面的，替换custom.gz

**Comment by RideWindOne** [comment]
终于解决问题了，，，原来是因为ixgbe的驱动问题导致的。。因为我需要ixgbevf，然后把ixgbe和ixgbevf都编译了。然后导致找不到IP 。不知道是这两个不能同时编译还是ixgbe有问题。

**Comment by wjz304** [comment]
解决了就好，昨晚比较忙，还没抽出时间看
