### ISSUE TITLE
Custom dsm111

### ISSUE THREAD

**Issue by hotpigwk** [wjz304/Redpill_CustomBuild#4465]
{"platform":"DS3617xs","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x0781","pid":"0x5571","diskidxmap":"00","sataportmap":"6","ext":"r8168,e1000e","exp":"pocopico","jun":"1"}

**Comment by wjz304** [comment]
什么浏览器？

**Comment by hotpigwk** [comment]
我用的浏览器倒是edge ，不过现在已经不是大的问题了。X79的主板，e5的cpu怎么好像很难装黑裙引导的样子，是么？弄了几次，结果都在开始安装之前就卡住了，显示2，3、4、5、6驱动器故障，所以暂停安装。我回头试试把sataidmap改成1看看，但我之前在core系统里面查到的是6。

多谢指点！
 


240933
 
From: Ing
Date: 2022-09-20 11:00
To: wjz304/Redpill_CustomBuild
CC: hotpigwk; Author
Subject: Re: [wjz304/Redpill_CustomBuild] Custom dsm111 (Issue #4465)
什么浏览器？

**Comment by wjz304** [comment]
> 我用的浏览器倒是edge ，不过现在已经不是大的问题了。X79的主板，e5的cpu怎么好像很难装黑裙引导的样子，是么？弄了几次，结果都在开始安装之前就卡住了，显示2，3、4、5、6驱动器故障，所以暂停安装。我回头试试把sataidmap改成1看看，但我之前在core系统里面查到的是6。 多谢指点！ 240933 From: Ing Date: 2022-09-20 11:00 To: wjz304/Redpill_CustomBuild CC: hotpigwk; Author Subject: Re: [wjz304/Redpill_CustomBuild] Custom dsm111 (Issue #4465) 什么浏览器？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

哦，正常如果从web 创建 7.1.1-42962 jun是选不了1的，所以确定下是不是有bug。
E5确实问题多多
