### ISSUE TITLE
请问sata驱动需不需要编译

### ISSUE THREAD

**Issue by swhoro** [wjz304/Redpill_CustomBuild#4479]
华擎h310cm itx/ac主板
只找到了intel 219网卡需要的e1000e驱动
但是貌似驱动网址里面还有个sata驱动列表？找不到主板对应的是哪一个
以及还需不需要编译其它驱动？

**Comment by wjz304** [comment]
正常普通家用pc主板 没有 扩展卡，除了网卡不需要其他的了

**Comment by swhoro** [comment]
> 正常普通家用pc主板 没有 扩展卡，除了网卡不需要其他的了

 谢谢
