### ISSUE TITLE
Custom woniubshuang3617 

### ISSUE THREAD

**Issue by Phachd** [wjz304/Redpill_CustomBuild#4485]
{
  "platform": "DS3617xs",
  "version": "7.1.1-42962",
  "maxlanport": "7",
  "internalportcfg": "0xffff",
  "netif_num": "2",
  "vid": "0x0781",
  "pid": "0x5583",
  "diskidxmap": "00",
  "sataportmap": "24",
  "sasidxmap": "0",
  "ext": "e1000e,igb,ixgbe,dtb-patch,vmxnet3,redpill,https://raw.githubusercontent.com/jumkey/redpill-load/develop/redpill-acpid/rpext-index.json",
  "exp": "pocopico",
  "jun": "0"
}

**Comment by Phachd** [comment]
add schedule

**Comment by Phachd** [comment]
delete builds

**Comment by wjz304** [comment]
没看到你加 schedule 的 commit 啊？
