### ISSUE TITLE
好TM强大啊

### ISSUE THREAD

**Issue by htmambo** [wjz304/Redpill_CustomBuild#456]
![image](https://user-images.githubusercontent.com/14806317/184538748-f5da1830-a113-452c-bf4a-1a3f801d70ce.png)
这个有可能会导致自动加载的这些内容出不来

**Comment by wjz304** [comment]
超一定次数后需要鉴权，

**Comment by htmambo** [comment]
这是我这儿的运营商搞地鬼啊，域名都解析不了。索性给dns也搞到软路由里去算了。

**Comment by wjz304** [comment]
https://github.com/isevenluo/github-hosts
+
https://github.com/oldj/SwitchHosts

**Comment by wjz304** [comment]
+
https://github.com/yichengchen/clashX
😁

**Comment by htmambo** [comment]
你说的这几个我都有，不过基本上没用，一直是nas里跑了个openwrt当旁路由在搞
