### ISSUE TITLE
关于 dtb 自定义参数的形式

### ISSUE THREAD

**Issue by wjz304** [wjz304/Redpill_CustomBuild#47]
目前没有很好的传参形式，如果有想法欢迎提出来，大家一起讨论，或者直接提PR。

# 大家上传的附件, 测试OK以后, 建议更新下备注, 一是分享给更多同型号的人, 二是也方便自己日后确认不是~

# 实在不会可以入群, 找群管理.

**Comment by wjz304** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip)

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/182204758-ec52b8a3-88f8-49a0-a9e2-83dc13872a4b.png)

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/182205365-5e35e286-4d72-40b0-8e22-074faff13dec.png)

**Comment by wjz304** [comment]
目前采用 文件下载的形式，因此 dtb 请传一个dtb文件的下载链接，

github Issues 附件即可获取到链接，参考上面截图（由于github限制只能传压缩包，所以请将 .dts / .dtb 文件压缩为 .zip 或者 .tar.gz 后上传会自动解压处理）。

如果传 .dts 文件，将自动转为 .dtb 文件后使用，
如果传 .dtb 文件，则直接使用。

**Comment by psp271** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip

**Comment by wjz304** [comment]
判断一个URL是否有效的方法：
点击这个地址（在浏览器打开）会自动下载，并不是打开一个web页面，
如果是打开的一个web页面，编译过程中下载的就是这个web页面的html文件，并不是压缩包文件。

**Comment by nforce4-csu** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9270219/ds920p.zip)

**Comment by nforce4-csu** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9270299/ds920p.zip)
测试一下！！

**Comment by seauvv** [comment]
[Uploading ds920p.zip…]()

**Comment by seauvv** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9276137/ds920p.zip)

**Comment by seauvv** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9285441/ds920p.zip)

**Comment by seauvv** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9289601/ds920p.zip)

**Comment by daianko** [comment]
[ds920dts.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9387642/ds920dts.zip)

**Comment by sgy0601** [comment]
咋上传呢？？？？？？？？、、
[Uploading ds920p.zip…]()
？

**Comment by sgy0601** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9414912/ds920p.zip)

**Comment by daianko** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9416195/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9417203/ds920p.zip)

**Comment by 521655** [comment]
[ds920p (8).zip](https://github.com/wjz304/Redpill_CustomBuild/files/9417554/ds920p.8.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9420817/ds920p.zip)

**Comment by abe520** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9423454/ds920p.zip)
蜗牛B

**Comment by 521655** [comment]
[ds920p (2).zip](https://github.com/wjz304/Redpill_CustomBuild/files/9425484/ds920p.2.zip)

**Comment by 521655** [comment]
[ds920p (3).zip](https://github.com/wjz304/Redpill_CustomBuild/files/9425831/ds920p.3.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9425976/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9426302/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9426558/ds920p.zip)

**Comment by 521655** [comment]
[ds920p (2).zip](https://github.com/wjz304/Redpill_CustomBuild/files/9427137/ds920p.2.zip)

**Comment by 521655** [comment]
[ds920p (2).zip](https://github.com/wjz304/Redpill_CustomBuild/files/9427185/ds920p.2.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9429378/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9437594/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9437619/ds920p.zip)

**Comment by 521655** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9438009/ds920p.zip)

**Comment by daianko** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9439373/ds920p.zip)

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9462600/ds920p.zip)

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9465934/ds920p.zip)

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9468262/ds920p.zip)

**Comment by wjz304** [comment]
curl https://raw.githubusercontent.com/pocopico/tinycore-redpill/main/rploader.sh
sed -i 's/patchdtc)/patchdtc2)\n    patchdtc\n    ;;\npatchdtc)/g' ./rploader.sh
TARGET_PLATFORM="geminilake" ./rploader.sh patchdtc2         #DS920+
TARGET_PLATFORM="v1000" ./rploader.sh patchdtc2                 #DS1621+
TARGET_PLATFORM="dva1622" ./rploader.sh patchdtc2             #DAV1622

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9470387/ds920p.zip)

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9470552/ds920p.zip)

**Comment by Chocky1126** [comment]
[ds920p_dts.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9474327/ds920p_dts.zip)

**Comment by abe520** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9479587/ds920p.zip)
蜗牛B

**Comment by jnlpc123** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9531529/model_ds920p.zip)

**Comment by jnlpc123** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9539699/model_ds920p.zip)

**Comment by tracemouse** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9539956/ds920p.zip)

**Comment by jwzj2020** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9555531/model_ds920p.zip)

**Comment by ybml2019** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9579837/ds920p.zip)

**Comment by ybml2019** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9590827/ds920p.zip)

**Comment by zuotf** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip)

**Comment by jwzj2020** [comment]
[model_ds1621p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9591761/model_ds1621p.zip)

**Comment by jwzj2020** [comment]
[Uploading model_dva1622.zip…]()

**Comment by Swiftfrog** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9592968/ds920p.zip)

**Comment by orannnnnnge** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9597218/model_ds920p.zip)

**Comment by 157843320** [comment]
[ds920p.zip(https://github.com/wjz304/Redpill_CustomBuild/files/9597218/model_ds920p.zip)]

**Comment by 157843320** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/9597218/model_ds920p.zip

**Comment by 157843320** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9601243/ds920p.zip)

**Comment by 157843320** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9608792/ds920p.zip)

**Comment by 157843320** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9618734/ds920p.zip)

**Comment by daianko** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9633189/ds920p.zip)

**Comment by daianko** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9633802/ds920p.zip)

**Comment by seauvv** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9634244/ds920p.zip)

**Comment by aak6102** [comment]
[ds920p_TS_453Dmini.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9634692/ds920p_TS_453Dmini.zip)

**Comment by ghost9394** [comment]
[1621p.zip] 
[model_ds1621p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9644858/model_ds1621p.zip)

**Comment by seauvv** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9646886/ds920p.zip)
ceshi

**Comment by Alex57996611** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip

**Comment by gzxiexl** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9658328/ds920p.zip)

**Comment by surprise007** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip

**Comment by surprise007** [comment]
(https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip)

**Comment by molly77** [comment]
[ds920p2.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9684553/ds920p2.zip)

**Comment by yu3651** [comment]
[model.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9686455/model.zip)

**Comment by DarkDreamDark** [comment]
> curl https://raw.githubusercontent.com/pocopico/tinycore-redpill/main/rploader.sh
> sed -i 's/patchdtc)/patchdtc2)\n    patchdtc\n    ;;\npatchdtc)/g' ./rploader.sh
> TARGET_PLATFORM="geminilake" ./rploader.sh patchdtc2         #DS920+
> TARGET_PLATFORM="v1000" ./rploader.sh patchdtc2                 #DS1621+
> TARGET_PLATFORM="dva1622" ./rploader.sh patchdtc2             #DAV1622

不明白这个该怎么用？能否出个教程教下dtb文件怎么获取

**Comment by zuotf** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9235849/ds920p.zip)

**Comment by wjz304** [comment]
> > curl https://raw.githubusercontent.com/pocopico/tinycore-redpill/main/rploader.sh
> > sed -i 's/patchdtc)/patchdtc2)\n    patchdtc\n    ;;\npatchdtc)/g' ./rploader.sh
> > TARGET_PLATFORM="geminilake" ./rploader.sh patchdtc2         #DS920+
> > TARGET_PLATFORM="v1000" ./rploader.sh patchdtc2                 #DS1621+
> > TARGET_PLATFORM="dva1622" ./rploader.sh patchdtc2             #DAV1622
> 
> 不明白这个该怎么用？能否出个教程教下dtb文件怎么获取

这些天搬家没开电脑，等国庆之后吧

**Comment by ccMax00** [comment]
[ds920p.zip (https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip)

**Comment by paulking644** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9741438/model_ds920p.zip)
esxi通用dtb

**Comment by gzxiexl** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9743153/ds920p.zip)

**Comment by hanshan2000** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9745799/ds920p.zip)

**Comment by qianyuanaini** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9753296/ds920p.zip)

**Comment by yanchu0812** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9787933/ds920p.zip)

**Comment by wthcrb** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9791417/ds920p.zip)

**Comment by wthcrb** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9791441/ds920p.zip)
测试

**Comment by wthcrb** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9791471/ds920p.zip)
映泰j4125

**Comment by CoStark-ZK** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9808660/ds920p.zip)

**Comment by CoStark-ZK** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9809900/ds920p.zip)

**Comment by wjz304** [comment]
> jumkey在5月21日开发出了auto patch dtb，可以实现自动编译dtb文件，因此对于DS920等需要设备树（dtb）的机型,如果使用4个及4个以下硬盘的，完全不用自己去测试和编辑，自动识别你的硬盘。是否可以实现编译的时候默认选择auto patch dtb，对于需要4盘位以上的需求，则选择自定义dtb。 ![image](https://user-images.githubusercontent.com/65521882/196581628-c4e00291-23b9-45bf-930c-eff548e40416.png)

https://github.com/wjz304/Redpill_CustomBuild/commit/d8fa62910f32add319ee2726cec6cf9c9d38b8eb

**Comment by w2861** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9849054/ds920p.zip)

**Comment by Vivi-Chen** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip

**Comment by Vivi-Chen** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip)

**Comment by finalstart2020** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9872814/ds920p.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9930800/ds920.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9940414/ds920.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9942590/ds920.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9942625/ds920.zip)

**Comment by willan007** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9944027/ds920p.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9944090/ds920.zip)

**Comment by willan007** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9996886/ds920.zip)

**Comment by xiaomuwu123** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10031620/ds920p.zip)

**Comment by sgy0601** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10045569/ds920p.zip)

**Comment by veeoit** [comment]
[ds920p-6.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10045866/ds920p-6.zip)

**Comment by slp10230102** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9235849/ds920p.zip)

**Comment by wxlxp** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10055841/ds920p.zip)

**Comment by wxlxp** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10067397/model_ds920p.zip)

**Comment by reyukari** [comment]
[ds920](https://c.patchouliqbot.top:5001/sharing/uMWZ7Hars)
测试链接

**Comment by qqwqtzd** [comment]
[model.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10095832/model.zip)

**Comment by wxlxp** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10098070/ds920p.zip)

**Comment by wxlxp** [comment]
[ds920p-401.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10101386/ds920p-401.zip)

**Comment by wjz304** [comment]
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10111193/output.zip)

**Comment by reyukari** [comment]
[output.dtb.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10141680/output.dtb.zip)
测试

**Comment by syxuxiaoliang** [comment]
测试

**Comment by syxuxiaoliang** [comment]
[Uploading ds920p.zip…]()
N5105可用，ESXI

**Comment by syxuxiaoliang** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10151341/ds920p.zip)


畅网N5105可用，加一块Mpci-e转2口SATA卡，ESXI

**Comment by MadGhostcn** [comment]
[920cw5105.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10199468/920cw5105.zip)
CW-N5105-NAS sata 1-5 port
sata口从0开始，物理1-5，不使用原生口

**Comment by tbc0309** [comment]
[sa6400.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10242774/sa6400.zip)

**Comment by q923514555** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10243810/ds920p.zip)

**Comment by jun129** [comment]
微星 b360m gaming plus  主板6sata
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10289989/ds920p.zip)

**Comment by wyeen** [comment]
鑫炬火N5095主板M2固态硬盘DDR4内存台式机NAS 2.5G网囗12SATA
[DS920plus-2lan-12sata.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10303857/DS920plus-2lan-12sata.zip)
![O1CN01XGpM0A1efn1lr02Wb_!!87493899](https://user-images.githubusercontent.com/105848414/209559804-775d73b0-3947-438f-8799-058062b7cedd.jpg)

**Comment by ghxwzbc** [comment]
联想天逸510pro，支持一条nvm缓存
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10305144/ds920p.zip)

**Comment by wyeen** [comment]
[DS920plus.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10308354/DS920plus.zip)

**Comment by chdeast** [comment]
dell-ds920p-output.zip
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10334170/output.zip)

**Comment by XCQi** [comment]
[B250itx_YX.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10346277/B250itx_YX.zip)
DS920+ 云星B250itx 测试版

**Comment by unhoo28** [comment]
[jy_b660i.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10367790/jy_b660i.zip)

**Comment by fyjsy** [comment]
求华擎Z370M pro4板载6sata加2个nvme插满的DTS

**Comment by zergfff** [comment]
[ds1520p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10437940/ds1520p.zip)

**Comment by zergfff** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10438573/ds920p.zip)

**Comment by civilma** [comment]
> 

同求。

**Comment by civilma** [comment]
[
[DS920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10553664/DS920.zip)

**Comment by wjz304** [comment]
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10578801/output.zip)
SA6400 虚拟机

**Comment by civilma** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10610791/model_ds920p.zip)

**Comment by civilma** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10715843/model_ds920p.zip)

**Comment by pzploong** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10739302/model_ds920p.zip)

**Comment by tbc0309** [comment]
[Uploading model.zip…]()

**Comment by tbc0309** [comment]
[model.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10755789/model.zip)

**Comment by lzk508** [comment]
[ds923.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10774524/ds923.zip)

**Comment by civilma** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10788610/model_ds920p.zip)

**Comment by wzywzy74** [comment]
[ds920-dts.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10824296/ds920-dts.zip)

**Comment by wzywzy74** [comment]
[920_dts.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10832781/920_dts.zip)

**Comment by qq523046199** [comment]
测试

**Comment by ddk313** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10947767/ds920p.zip)

**Comment by ddk313** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10975285/model_ds920p.zip)

**Comment by MCAESOP** [comment]
七彩虹b250m-k 4sata+pcie转sata2个+1m.2 sata固态

[dva1622.zip](https://github.com/wjz304/Redpill_CustomBuild/files/10984159/dva1622.zip)

**Comment by MCAESOP** [comment]
[DVA1622 (2).zip](https://github.com/wjz304/Redpill_CustomBuild/files/10985193/DVA1622.2.zip)

**Comment by 9622315** [comment]
我也试试看

[NC98-LF_ds920p.dtb.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11011862/NC98-LF_ds920p.dtb.zip)
[NC98-LF_ds920p.dts.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11011863/NC98-LF_ds920p.dts.zip)

**Comment by jun129** [comment]
[b360m.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11132370/b360m.zip)

**Comment by jun129** [comment]
[b360m.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11132432/b360m.zip)

**Comment by intxzt** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11156681/ds920.zip)

**Comment by mycanfy** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11182434/model_ds920p.zip)
威联通DS453dmini，硬盘顺序与普通的相反，sata1~2：00:12.0，sata3~4：00:13.0,00.0

**Comment by mycanfy** [comment]
[model_ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11182461/model_ds920p.zip)
威联通453dmini，我这台sata硬盘口与别的相反，1~2口是0012，3~4口是0013

**Comment by JedMasterYoda** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11302785/ds920p.zip)
DIY的NAS测试下

**Comment by JedMasterYoda** [comment]
[Uploading ds920p.zip…]()

**Comment by JedMasterYoda** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11302848/ds920p.zip)

**Comment by JedMasterYoda** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11302966/ds920p.zip)

**Comment by finalstart2020** [comment]
no need



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月23日(周日) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wjz304/Redpill_CustomBuild] 关于 dtb 自定义参数的形式 (Issue #47)




 
ds920p.zip

**Comment by li0210** [comment]
[sa6400.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11304014/sa6400.zip)

**Comment by li0210** [comment]
[sa6400.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11304042/sa6400.zip)

**Comment by tly0729** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11456045/ds920p.zip)
123

**Comment by mycanfy** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11469000/ds920p.zip)
X86,满硬盘6个

**Comment by zlx84** [comment]
https://github.com/zlx84/Redpill_CustomBuild/blame/main/model_ds920p.dtb

**Comment by A10ss** [comment]
[ds1621p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11582793/ds1621p.zip)

**Comment by tom-temp** [comment]
hp400g1，dts文件，,"ext":"e1000,e1000e,igb"
[hp400g1-ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11857180/hp400g1-ds920.zip)

**Comment by lthytdcf** [comment]
923 @

**Comment by lthytdcf** [comment]
[923-8SATA.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11857279/923-8SATA.zip)

**Comment by chdeast** [comment]
ds920
[ds920-d.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11878991/ds920-d.zip)

**Comment by chdeast** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/11878991/ds920-d.zip

**Comment by chdeast** [comment]
https://github.com/wjz304/Redpill_CustomBuild/files/11878991/ds920-d.zip

**Comment by chdeast** [comment]
ds920+,cpu4570,r8169
[DS920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/11925354/DS920.zip)

**Comment by songmiaoxyk** [comment]
> 

[ds920sm.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12179334/ds920sm.zip)

**Comment by songmiaoxyk** [comment]
[ds920ss.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12180368/ds920ss.zip)

**Comment by Mr-hsing** [comment]
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12192022/output.zip)

**Comment by Mr-hsing** [comment]
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12215991/output.zip)

**Comment by songmiaoxyk** [comment]
[thinkpad920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12265408/thinkpad920.zip)

**Comment by xiao-dd** [comment]
[https://github.com/xiao-dd/Build-OpenWrt/blob/main/output.zip](url)

**Comment by xiao-dd** [comment]
ds920d
[output.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12340892/output.zip)

**Comment by xiao-dd** [comment]
ds92d
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12341005/ds920p.zip)

**Comment by DevilOrDemon** [comment]
[ds920.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12440654/ds920.zip)
ds920+
云星b365主板，r8125双2.5g网口，6sata接口（只插了一个硬盘）

**Comment by DevilOrDemon** [comment]
[ds920p.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12445445/ds920p.zip)

**Comment by Mangshite** [comment]
[
[ds920p.dtsxc.zip](https://github.com/wjz304/Redpill_CustomBuild/files/12641800/ds920p.dtsxc.zip)
](url)

**Comment by iphonetlbs** [comment]
[model_ds923p.zip](https://github.com/wjz304/rpcb/files/12774569/model_ds923p.zip)

**Comment by PaulYuuu** [comment]
[ds923p.zip](https://github.com/wjz304/rpcb/files/12840906/ds923p.zip)

**Comment by chdeast** [comment]
ds920，用于dell
[ds920dtb.zip](https://github.com/wjz304/rpcb/files/13161071/ds920dtb.zip)
