### ISSUE TITLE
其他型号的群晖引导编译

### ISSUE THREAD

**Issue by flyubuntu** [wjz304/Redpill_CustomBuild#48]
有没有其他型号的群晖引导编译呢,例如我想编译一个DS220+ 型号的,该型号和京东有一个合作,可以生产京豆.恰好我也有该型号对应的洗白码,想试一试~~

**Comment by wjz304** [comment]
DS220+目前是没办法了，所有大佬的驱动库都没有该型号的兼容，

**Comment by wjz304** [comment]
你可以试试 
![image](https://user-images.githubusercontent.com/5615843/182086251-f0478b5b-6370-4c47-8c51-d77304a8d9ec.png)
导入一个 220的映像看看能不能创建

**Comment by flyubuntu** [comment]
这个方案试过了,提示我映像不兼容.必须传VM映像

**Comment by wjz304** [comment]
有 220+ 的 sn吗？ 发个假的就行，看下 规则和mac，尝试编译下

**Comment by wjz304** [comment]
或者 你改下这个 引导里的 sn和 mac 看看能不能起来，https://github.com/wjz304/Redpill_CustomBuild/actions/runs/2873181965
(采用920 偷梁换柱的方式，虽然名字是920 但是内部的pat都是用的220的)
