### ISSUE TITLE
Custom 624-2

### ISSUE THREAD

**Issue by im5a** [wjz304/Redpill_CustomBuild#48958]
{"model":"DS3617xs","version":"6.2.4-25556","jun":"1","lkm":"dev","maxlanport":"7","netif_num":"2","vid":"0x0951","pid":"0x1666","diskidxmap":"0006","sataportmap":"62","sasidxmap":"0","modules":"r8152,r8169"}

**Comment by ron44-5** [comment]
> {"model":"DS3617xs","version":"6.2.4-25556","jun":"1","lkm":"dev","maxlanport":"7","netif_num":"2","vid":"0x0951","pid":"0x1666","diskidxmap":"0006","sataportmap":"62","sasidxmap":"0","modules":"r8152,r8169"}
