### ISSUE TITLE
Custom ak6102_ds920 _7.1

### ISSUE THREAD

**Issue by Lilei6102** [wjz304/Redpill_CustomBuild#4991]
{"platform":"DS920+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x46f4","pid":"0x0001","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/9235785/ds920p.zip","ext":"r8125,e1000","exp":"pocopico","jun":"0"}

**Comment by aak6102** [comment]
只能识别2个硬盘
