### ISSUE TITLE
Custom 2022-08-17-3622

### ISSUE THREAD

**Issue by timo-hu** [wjz304/Redpill_CustomBuild#521]
{
"platform":"DS3622xs+",
"version":"7.0.1-42218",
"jun":"1",
"exp": "jumkey",
"sn":"2250V8RZCG530",
"mac":"00113288TIMO",
"ext":" r8168, tg3"
}

**Comment by wjz304** [comment]
没意外 你这个mac 是无效的 00113288TIMO
