### ISSUE TITLE
Custom Angel_Gen8 2022-08-17

### ISSUE THREAD

**Issue by maglcal** [wjz304/Redpill_CustomBuild#535]
{"platform":"DS918+","version":"7.1.0-42661","usb":"0x0001, 0x46f4","ext":"e1000,e1000e,vmxnet3,tg3","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/185152191-7527f9f1-4841-4eaa-8ca0-2ec13fa4e17f.png)
