### ISSUE TITLE
Custom 9-25test

### ISSUE THREAD

**Issue by redsunboy** [wjz304/Redpill_CustomBuild#5499]
{"platform":"DS918+","version":"7.1.1-42962","maxdisks":"4","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x05E3  ","pid":"0x0749","ext":"r8125,e1000e,r8101,e1000,bnx2,bnx2x,rtl8150","exp":"pocopico","jun":"1","dev":"1"}

**Comment by wjz304** [comment]
pocopico 大修改了 tinycore-redpill 的分支, 导致算号脚本获取失败, 已修改。
