### ISSUE TITLE
编译出来的引导无法识别直通的sata控制器

### ISSUE THREAD

**Issue by magic-monkey** [wjz304/Redpill_CustomBuild#5792]
{
    "info":"不再接受 SN/MAC 的定制, 请勿输入! 任何不读注意事项就创建的行为都是耍流氓!",
    "platform":"DS3622xs+",  
    "version":"7.0.1-42218",  
    "jun":"1",  
    "exp": "jumkey",  
    "ext":"r8125, e1000, e1000e, vmxnet3"  
}
不管用哪个版本编译出来的引导都没办法识别到直通的sata控制器，不知道是什么原因？

**Comment by wjz304** [comment]
抱歉，我没有硬件，所以不是很清楚
尝试加入控制器驱动
