### ISSUE TITLE
Custom 2022-08-21

### ISSUE THREAD

**Issue by lingking91** [wjz304/Redpill_CustomBuild#639]
{"platform":"DS920+","version":"7.1.0-42661","map":"2，00","dtb":"https://github.com/pocopico/tinycore-redpill/blob/main/ds920p.dts","usb":"0x0781, 0x5571","ext":"r8125","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
dts文件有错误，第8行 1-2字符
![image](https://user-images.githubusercontent.com/5615843/186164477-0388bda1-4680-41ff-9509-6b4588aa9c71.png)
