### ISSUE TITLE
Custom { }

### ISSUE THREAD

**Issue by zhengchao666abc** [wjz304/Redpill_CustomBuild#698]
{"platform":"DS918+", "version":"7.1.1-42951", "jun":"1", "ext":"r8125,r8168"}

**Comment by zhengchao666abc** [comment]
{"platform":"DS918+", "version":"7.1.1-42951", "jun":"1", "ext":"r8125,r8168"}

**Comment by zhengchao666abc** [comment]
> {"platform":"DS918+", "version":"7.1.1-42951", "jun":"1", "ext":"r8125,r8168"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/186164144-05c01760-3898-4980-9a64-ddbabe26b877.png)
