### ISSUE TITLE
Custom jj-11

### ISSUE THREAD

**Issue by mm5425** [wjz304/Redpill_CustomBuild#7384]
{"platform":"DS3617xs","version":"7.1.1-42962","maxdisks":"6","maxlanport":"7","internalportcfg":"0xffff","netif_num":"4","vid":"0x46f4","pid":"0x0001","diskidxmap":"00","sataportmap":"6,00","ext":"r8169,rtl8150,r8168,r8152,r8125,r8101,e1000e,e1000,vmxnet3,vmw_pvscsi,via-rhine,v9fs,tn40xx,vxge,wch,sfc,skge,sky2,tg3,8139cp,8139too,aacraid,-virtio,-acpid2,-misc","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
目测 微软服务器压力过大，没有触发编译， 过会再试吧
