### ISSUE TITLE
Custom 1231

### ISSUE THREAD

**Issue by 676507076** [wjz304/Redpill_CustomBuild#7400]
{"platform":"DS3617xs","version":"7.0.1-42218","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x090C","pid":"0x000F","ext":"r8168,r8125","exp":"jumkey","jun":"1"}

**Comment by wjz304** [comment]
目测 微软服务器压力过大，延时很高， 建议过一段时间再试
