### ISSUE TITLE
DS918+7.1.1-42962

### ISSUE THREAD

**Issue by zwd5168** [wjz304/Redpill_CustomBuild#7401]
{"平台":"DS918+","版本":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"1","vid":" 0x0781","pid":"0x5583","diskidxmap":"000150","sataportmap":"458","ext":"r8101,r8168,r8169,8139cp,8139too,,RTL8111H","exp": "pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
目测 微软服务器压力过大，延时很高， 建议过一段时间再试
