### ISSUE TITLE
Custom 918++

### ISSUE THREAD

**Issue by songmiao8888** [wjz304/Redpill_CustomBuild#800]
{"platform":"DS918+","version":"7.1.1-42951","map":"4,00","exp":"pocopico","usb":"0x6545, 0x0930","mac":"001132888A95, 001132888A96,001132888A97,001132888A98","ext":"r8125, r8168, e1000e, igb, vmxnet3, ixgbe","dev":"1"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/186845796-9ef6cb2b-5fb4-4942-97d5-3f37dcd2277c.png)
