### ISSUE TITLE
Custom 3622xs  dell 730xd 221010 7.01 jun jumke

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#8177]
{"platform":"DS3622xs+","version":"7.0.1-42218","maxdisks":"32","maxlanport":"31","internalportcfg":"0xffff","netif_num":"8","vid":"0x0930","pid":"0x6544","ext":"mpt3sas,igb,ixgbe,e1000e,https://raw.githubusercontent.com/wjz304/rp-ext/main/lsiutil/rpext-index.json","exp":"jumkey","jun":"1"}

**Comment by chenjihong99** [comment]
你好，我的服务器配置和你的完全一样，请问目前你的配置成功了吗
