### ISSUE TITLE
Custom PanWaifongNAS

### ISSUE THREAD

**Issue by PanWaifong** [wjz304/Redpill_CustomBuild#8186]
{"platform":"DS918+","version":"7.1.1-42962","maxlanport":"7","internalportcfg":"0xffff","netif_num":"2","vid":"0x4146","pid":"0xBA65","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
日期: 2022/10/10 1:48:02 提交代码有遗漏，导致dev模式下均会失败，已修复。
