### ISSUE TITLE
custom 920

### ISSUE THREAD

**Issue by psp271** [wjz304/Redpill_CustomBuild#85]
{"platform":"DS920+", "version":"7.0.1-42218", "dtb": "https://raw.githubusercontent.com/psp271/Redpill_CustomBuild/main/ds920p.zip", "ext":"r8169"}

**Comment by wjz304** [comment]
你这个链接是网页页面的链接，

正确的文件的下载地址应该是这个地址。
https://raw.githubusercontent.com/psp271/Redpill_CustomBuild/main/ds920p.zip

**Comment by wjz304** [comment]
简单判断 就是 点击这个地址会自动下载，并不是打开一个web，否则代码中下载的就是页面的 html 文本文件，
