### ISSUE TITLE
custom test

### ISSUE THREAD

**Issue by cdmxp** [wjz304/Redpill_CustomBuild#90]
{"platform":"DS918+", "version":"7.0.1-42218", "jun":"1", "map":"22, 0002", "usb":"0x0d5c, 0xa826","ext":"r8168"}

**Comment by cdmxp** [comment]
{"platform":"DS918+", "version":"7.0.1-42218", "jun":"1", "map":"22, 0002", "usb":"0x0d5c, 0xa826","ext":"r8168"}

**Comment by wjz304** [comment]
修改主体，编译不会获取后面的评论，容易冲突，太复杂了
