### ISSUE TITLE
Custom DS3617xs_6.2.4

### ISSUE THREAD

**Issue by holzkopf-yang** [wjz304/Redpill_CustomBuild#9314]
{
     "platform":"DS3617xs",  
     "version":"6.2.4-25556",
     "netif_num":"1",
     "mac1":"001132112255",
     "sn":"2021LWN123456",
    "vid":"0x8644",
    "pid":"0x8003",
    "sataportmap":"4",
    "diskidxmap":"00",
    "sasidxmap":"0",
    "jun":"0",
   "exp":"jumkey"
}

**Comment by holzkopf-yang** [comment]
delete builds

**Comment by holzkopf-yang** [comment]
DS3617xs 6.2.4-25556
Run Build 报错：
============================编译开始============================
Cloning into 'redpill-load'...
===========================7.1 解密PAT==========================
===========================添加必备驱动==========================
=======================Download redpill.ko======================
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Error: Process completed with exit code 1.

**Comment by wjz304** [comment]
3617 没有6.2.4，请使用 web构建，会屏蔽掉 一些问题。
