### ISSUE TITLE
Custom

### ISSUE THREAD

**Issue by nh-ojs** [wjz304/Redpill_CustomBuild#94]
{"platform":"DS3622xs+","version":"7.1.0-42661","map":"","dtb":"","sn":"","mac":"","usb":"0x0001, 0x46f4","ext":"","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
刚发现html 有个bug，platform 中的+号会丢失

**Comment by wjz304** [comment]
修复了，但是可能要清浏览器缓存才会生效。
