### ISSUE TITLE
Custom 

### ISSUE THREAD

**Issue by htmambo** [wjz304/Redpill_CustomBuild#97]
{"platform":"DS918+","version":"7.0.1-42218","map":"22,0002","dtb":"","sn":"","mac":"","usb":"0x0001, 0x46f4","ext":"r8125","exp":"jumkey","jun":"1"}

**Comment by wjz304** [comment]
你这是测试我的能力啊，哈哈

**Comment by wjz304** [comment]
改完可以 reopen 触发了

**Comment by htmambo** [comment]
这个字段内容的填写我有点头疼，每次得去翻你的readme。这次是随便写地，结果就写错了。

**Comment by htmambo** [comment]
[](url)

**Comment by wjz304** [comment]
搞个复选框？

**Comment by wjz304** [comment]
我不会前端，现在的是copy actions里的

**Comment by htmambo** [comment]
前端我稍微会一点，可以尝试折腾折腾看看

**Comment by wjz304** [comment]
https://supes.top/?version=22.03&target=x86%2F64&id=generic  
![image](https://user-images.githubusercontent.com/5615843/183037747-cc51dbd3-2a51-49e9-bd4d-98a9b017ab40.png)
他这个效果挺好的

**Comment by htmambo** [comment]
嗯，可以考虑用一些前端框架，然后自动抓取一些列表什么地，这个我考虑一下怎么抓，怎么解析。好在这玩意大部分都是json格式的，好办一些

**Comment by htmambo** [comment]
我先给整理一下资料自己先尝试一下。

**Comment by wjz304** [comment]
看你的了

**Comment by htmambo** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/14806317/183047522-63734a0a-8650-4283-8836-dfdbad3e37f5.png">
目前，界面这里已经完全根据你的yaml来自动生成了。晚上回家继续搞

**Comment by htmambo** [comment]
后面这里针对ext再去看看那些基础库有没有总列表什么地。然后给做成类似你上面提到的那种样式

**Comment by htmambo** [comment]
另外这个required字段的分析以及对表单的验证后面也要考虑一下。

**Comment by htmambo** [comment]
使用说明那里来自于你的description字段

**Comment by wjz304** [comment]
```
  <script>
    function httpGetAsync(theUrl, callback) {
      let xmlHttpReq = new XMLHttpRequest();
      xmlHttpReq.onreadystatechange = function () {
        if (xmlHttpReq.readyState == 4 && xmlHttpReq.status == 200)
          callback(xmlHttpReq.responseText);
      }
      xmlHttpReq.open("GET", theUrl, true); // true for asynchronous 
      xmlHttpReq.send(null);
    }

    httpGetAsync('https://raw.githubusercontent.com/pocopico/rp-ext/main/exts', function(result){
        console.log(result);
        //
    });

这个可以拿到
```

**Comment by htmambo** [comment]
好的，不会用Github，这玩意居然说密码什么2021年移除了。我得打包放nas里去同步

**Comment by htmambo** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/14806317/183050231-ccce6bc9-d6a2-4886-bb55-58ddf2f0941d.png">
目前长这样，你可以考虑加个字段让我用来做标题，然后你再把每个Desc那个字段写详细一点我就直接套用上了

**Comment by wjz304** [comment]
加不了参数了啊，

**Comment by htmambo** [comment]
嗯，我先把上面那个列表加进来折腾

**Comment by htmambo** [comment]
![image](https://user-images.githubusercontent.com/14806317/183064127-6bcbf688-2615-46a8-865a-f72d36336157.png)
大致上的样子已经出来了，下来把这个Ext的事件完善一下就可以了

**Comment by htmambo** [comment]
[归档.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9268102/default.zip)
需要引入一个js用来解析yaml格式的文件，所以，需要你部署以后，将原文中的
`<script src="./dist/yaml.js"></script>`
这里的位置给修复正确

**Comment by htmambo** [comment]
[归档.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9268133/default.zip)
要引入一个js文件用来解析yaml，所以你需要将原文中的
`<script src="./dist/yaml.js"></script>`
中的位置修复成正确的位置

**Comment by htmambo** [comment]
![image](https://user-images.githubusercontent.com/14806317/183068111-7f6abf4e-6248-4968-b044-8b75e3d9b897.png)
最终的效果图大致上是这样的，不清楚这自带的Css里都有哪些样式，盲猜了个btn-danger居然还能用就给用上了。反正有个区别就行。

**Comment by wjz304** [comment]
提交了

**Comment by htmambo** [comment]
我的网络一直获取这个地址有问题：
`https://raw.githubusercontent.com/wjz304/Redpill_CustomBuild/main/.github/workflows/custom.yml`
你这个yaml的inputs其实是固定的，后面可以考虑不需要执行这一步

**Comment by wjz304** [comment]
> 我的网络一直获取这个地址有问题： `https://raw.githubusercontent.com/wjz304/Redpill_CustomBuild/main/.github/workflows/custom.yml` 你这个yaml的inputs其实是固定的，后面可以考虑不需要执行这一步

墙的问题？还是权限问题？

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/183086770-6614edc1-9152-45be-bdc9-8f44b6cc6edd.png)
😁😁😁

**Comment by htmambo** [comment]
这个太血腥了吧

**Comment by wjz304** [comment]
没啥艺术细胞，我就看这个牛逼，要不你挑一个：http://patorjk.com/software/taag/#p=testall&f=Graffiti&t=Redpill%20CustomBuild

**Comment by wjz304** [comment]
我也不会画图🤣

**Comment by htmambo** [comment]
![image](https://user-images.githubusercontent.com/14806317/183093523-069cd198-de61-4d03-9fab-a1f872b03eb1.png)
我黑苹果里shell用过它的ansi shadow，感觉很清晰

**Comment by wjz304** [comment]
其实我搞黑苹果 比黑群晖时间久😁 https://github.com/wjz304/Hackintosh-EFI-MSI-Z490i-Unify

**Comment by htmambo** [comment]
那这真是同道中人了啊，哈哈

**Comment by wjz304** [comment]
这 更血腥了吧🤣

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/183103137-0c203a5c-516c-4f8a-a554-25cbd58c6589.png)
听你的换了一个

**Comment by htmambo** [comment]
稍微改下样式吧，这个空行太高了。

**Comment by wjz304** [comment]
嗯，我看了，但是影响全局，我就没改。代码在这个库  https://github.com/wjz304/wjz304.github.io

**Comment by htmambo** [comment]
[untitled.html.zip](https://github.com/wjz304/Redpill_CustomBuild/files/9269741/untitled.html.zip)
comment里发不了html代码，你下载这个解压后在浏览器里看一下效果，稍微修改了一下样式。
`    font-size: 12px;
    line-height: 12px;
`
主要是这两句，如果感觉字号小，就同时调整一下这个12

**Comment by htmambo** [comment]
我好像忘了给红色取掉了，你搜索一下`color: red`自己处理一下吧

**Comment by wjz304** [comment]
红的吧，看着也还行

**Comment by wjz304** [comment]
这个之前倒是考虑过上传到国内网盘，但是没有好的选择

**Comment by htmambo** [comment]
我这个蜗牛也搞不定920，加了一堆网卡驱动，就是死活找不到

**Comment by htmambo** [comment]
页面里的pre后面的Style的内容换成这个吧：
`
style="font-family: ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace !important;
    font-size: 12px !important;
    line-height: 12px !important;
    margin: 15px 10px;
    color: red;"
`
清除了每行的空距，换了个字体

**Comment by htmambo** [comment]
![image](https://user-images.githubusercontent.com/14806317/183108509-04c7495f-e1e7-43a3-a4ce-01e034de9040.png)

看起来就是这个样子，比那种默认的有行距的看起来能舒服些

**Comment by wjz304** [comment]
提上去了

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/183358302-e85c2a46-9045-4289-bdf5-4de7712d8571.png)
有个bug，这个 ext 不变红，再点也删不掉，就他的name中有点

**Comment by wjz304** [comment]
obj.addClass("btn-danger"); 不生效

**Comment by wjz304** [comment]
改好了，
