### ISSUE TITLE
Custom 3622xs 2308 540

### ISSUE THREAD

**Issue by lichangfeng-1** [wjz304/Redpill_CustomBuild#972]
{
  "platform": "DS3622xs+",
  "version": "7.0.1-42218",
  "map": "1, 10",
  "usb": "0x6544, 0x0930",
  "jun": "1",
  "exp": "jumkey",
  "mac": "001132888A95, 001132888A96",
  "ext": "r8125, e1000, e1000e, vmxnet3,mpt3sas, https://raw.githubusercontent.com/wjz304/rp-ext/main/rtl8150/rpext-index.json,arcmsr,mptsas,mptspi,megaraid_sas,ixgbe,ixgbevf,dtb-patch,aic94xx"
}

**Comment by wjz304** [comment]
抱歉，刚投的代码有遗漏导致错误提示
