### ISSUE TITLE
Custom lsi驱动

### ISSUE THREAD

**Issue by xinmiti** [wjz304/Redpill_CustomBuild#986]
{"platform":"DS3622xs+","version":"7.1.1-42951","usb":"0x5583, 0x0781","ext":"mpt3sas,mptsas,mptspi,r8125","exp":"pocopico","jun":"0","dev":"1"}

**Comment by wjz304** [comment]
![image](https://user-images.githubusercontent.com/5615843/187341635-e68ce2d0-04ce-4497-bb7a-7bd0717db03a.png)
